version: 2
updates:
  # Node dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      node:
        patterns:
          - "*"

  # Ruby dependencies
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      ruby:
        patterns:
          - "*"

  # CI dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      ci:
        patterns:
          - "*"
